//
// Created by gohan on 19.05.2021.
//

#ifndef PROJECT_CONSTANTS_H
#define PROJECT_CONSTANTS_H
enum WINDOWS{WINDOW_MAIN,WINDOW_SIGNUP,WINDOW_LOGIN,WINDOW_ADMIN_PANEL,WINDOW_FILE_VIEW};
#endif //PROJECT_CONSTANTS_H
